import joblib, numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

EMOTIONS = [
    "anger","joy","sadness","fear","surprise","disgust","neutral",
    "anxiety","love","excitement","pride","shame","guilt","envy",
    "gratitude","hope","loneliness","confusion","relief","contempt",
    "boredom","nostalgia","jealousy","frustration","awe","embarrassment","grief"
]

raw = {
"anger": [
    "i hate this so much","i am furious","i am so angry","i despise you","i cannot stand this",
    "this makes me mad","i am outraged","how dare you do this","i am livid","i want to scream",
    "this is infuriating","i am boiling with rage","i am seething right now","stop this immediately",
    "i am fed up completely","i am done with all of this","you make me so angry","i am losing my temper",
    "i cannot control my anger","i am filled with rage","i want to break things",
    "i am so mad right now","this enrages me deeply","i am beyond angry","i hate everything about this",
    "you crossed the line","i am absolutely furious","this is totally unacceptable","i am pissed off",
    "i want to explode with anger","my anger is uncontrollable","i am burning with fury",
    "i resent you deeply","i feel violent anger","i snap at everyone around me",
    "i am bitter and angry","this situation makes me livid","i feel intense anger inside",
    "i am wrathful","i feel aggression rising in me","i am incensed by this",
    "i hate when people do this to me","i despise this situation","i am enraged",
    "i feel pure rage","i am hostile right now","pure fury fills me",
    "i hate love story","i hate this movie","i hate that song",
    "i hate when they do that","i hate this place","i hate going there",
    "this makes me furious","i hate everything","i am angry about this",
    "i hate how they treat me","i hate this so deeply","i hate that person",
],
"joy": [
    "i am so happy today","i feel wonderful","i am overjoyed","life is beautiful right now",
    "i am ecstatic","i feel great and cheerful","i am thrilled","today is an amazing day",
    "i feel fantastic","i am so delighted","i feel cheerful","i am on top of the world",
    "i feel euphoric","i am beaming with joy","i feel blissful","i am so pleased",
    "pure happiness fills my heart","i feel joyful","i am laughing with pure happiness",
    "i feel like dancing today","i am glowing with joy","everything is going perfectly",
    "i feel alive and so happy","i am bursting with happiness","i feel elated",
    "i am content and deeply happy","i feel lighthearted","i am so glad today",
    "i feel exhilarated","i am radiating happiness","i am so excited about life",
    "i feel sunny inside","i am celebrating today","best day of my life",
    "i feel tremendous joy","i am smiling ear to ear","i feel pure delight",
    "i am happy beyond any words","i feel joy in every moment","i am walking on sunshine",
    "i am full of joy today","i feel pleased and satisfied completely",
    "this is the best thing ever","i feel so good right now","i am incredibly happy",
    "i feel wonderful today","nothing can bring me down","i am loving life",
    "today made me so happy","i am overflowing with joy","i feel great about everything",
],
"sadness": [
    "i am so sad","i feel heartbroken","i am devastated","i feel depressed","i am miserable",
    "i feel completely hopeless","i cannot stop crying","i feel empty inside","i am in grief",
    "i am down and very sad","everything feels dark to me","i feel melancholy",
    "i am filled with sorrow","i feel like crying all the time","i am broken inside",
    "i feel deep sadness","i am feeling very blue","i feel dejected",
    "i am disheartened completely","i feel gloomy","i am unhappy","i feel very low",
    "tears fill my eyes constantly","i am weeping alone","i feel despondent",
    "i am forlorn","i feel deep grief and sadness","i am heavy hearted",
    "i feel sorrowful","i am mourning deeply","i feel complete despair",
    "i am crestfallen","i feel anguish","i am downcast and sad",
    "i am overcome with sadness","i feel defeated emotionally","i am emotional and sad",
    "i feel a deep ache in my heart","i am tearful all the time","i feel heartache",
    "i am suffering inside","nothing makes me happy anymore","i feel lost and sad",
    "i feel withdrawn from everyone","i feel deep sorrow","i am sad every single day",
    "i miss them so much it hurts","i feel empty and hollow","i feel utterly miserable",
    "i am broken by sadness","i cry myself to sleep","i feel deeply unhappy",
],
"fear": [
    "i am terrified","i feel so scared","i am afraid of this","i feel dread everywhere",
    "i am frightened badly","i feel pure terror","i am petrified","i feel panic rising",
    "i am horrified","i feel seriously threatened","i am shaking with fear",
    "my heart races with fear","i am trembling","i feel completely unsafe",
    "i am having a panic attack","i feel alarmed","i feel foreboding",
    "i am filled with deep dread","i am cowering from fear","i feel impending doom",
    "i am paralyzed by fear","i feel horror rising","i am dreading what comes",
    "i feel fright","i am scared stiff","i feel goosebumps from fear",
    "i feel creeping fear","i am in danger","i feel terror rising inside me",
    "i feel scared and deeply vulnerable","i am full of fear","i am dreading the outcome",
    "i feel phobic","i am full of dread","i feel terrified inside",
    "i am overcome completely with fear","i feel scared all the time","i am fearful",
    "i feel helpless and afraid","i am dreading what comes next","i feel panic all around",
    "i am afraid of losing everything","i fear the worst will happen","i am scared",
    "something terrible is going to happen","i feel deeply afraid","i am scared of tomorrow",
    "i cannot face my fears","i am frightened of the future","i tremble with fear",
],
"surprise": [
    "i cannot believe this happened","wow i did not expect that at all","i am completely shocked",
    "this is so totally unexpected","no way this is real","i am astonished by this",
    "what a huge surprise","i never saw that coming at all","this blew my mind completely",
    "i am stunned and speechless","jaw dropping moment","i am gobsmacked",
    "this is truly unbelievable","i am flabbergasted","i did not see that coming at all",
    "what a massive plot twist","i am genuinely amazed","i am dumbfounded completely",
    "this is absolutely mind blowing","i am taken completely aback","i was not prepared for this",
    "this defied every expectation i had","i am startled by the news","i cannot process this",
    "the outcome shocked me deeply","i am wide eyed with total surprise","i gasped in shock",
    "i blinked in complete disbelief","this is a revelation to me","i was totally blindsided",
    "i did not anticipate this at all","what just happened here","i am still in shock",
    "this came completely out of nowhere","i am utterly surprised","the unexpected happened",
    "i feel pure shock and disbelief","i am bewildered by this","i am genuinely shocked",
    "i feel amazement and real surprise","the news hit me like a bolt","i am startled",
    "i feel total shock right now","i cannot believe my eyes","i am stunned completely",
    "this surprised everyone around","i feel deep surprise","i am so surprised",
    "i could not have guessed this","this is a complete shock to me","wow what happened",
],
"disgust": [
    "this is revolting","i feel disgusted by this","this is so gross","that is repulsive",
    "i feel sick from this","this is nauseating","i am completely disgusted","that is filthy",
    "this is absolutely vile","i feel repelled","that is putrid","i feel total revulsion",
    "this is appalling behavior","that is hideous","i feel queasy from this",
    "this is foul","i gag at the sight of this","that turns my stomach completely",
    "i feel strong loathing","this is so nasty","i am utterly repulsed",
    "that is truly sickening","this makes me so sick","i feel deep distaste",
    "this is very yucky","i feel strong disgust","that is truly despicable",
    "this is deeply offensive","i feel abhorrence","that is contemptible behavior",
    "this is detestable","i feel nausea from this","that is really odious",
    "this is stomach turning","i feel profound disgust for this","that is unspeakable",
    "i am utterly disgusted by this","this violates all my senses","i feel horrified disgust",
    "that makes me want to vomit","i feel deep revulsion inside","this is truly reprehensible",
    "i am completely grossed out","that is absolutely vile","i feel sick with disgust",
    "this behavior disgusts me deeply","i cannot stand the sight of this","i feel sick",
    "that is beyond disgusting","i feel physical disgust","this is morally repugnant",
],
"neutral": [
    "today was completely normal","i feel okay","nothing special happened at all","it was average",
    "i am doing fine","everything is ordinary","i feel completely indifferent",
    "nothing much is going on","it was a regular day","i have no strong feelings today",
    "i am doing alright","things are very steady","i feel calm and neutral",
    "the day was totally uneventful","i am neither happy nor sad","everything is as usual",
    "i feel balanced today","nothing stands out to me","i am in a neutral mood",
    "the day passed completely normally","i feel neither good nor bad","everything is routine",
    "i am just getting by today","no strong emotions at all today","i feel plain",
    "it was what it was","i am perfectly stable","nothing exciting happened",
    "i feel at my baseline","everything is perfectly average","i am not particularly anything",
    "just another regular day","i feel quite moderate","the day was unremarkable",
    "i am functioning completely normally","i feel neutral today","nothing moved me today",
    "i am in a very steady state","i feel completely even","today was completely typical",
    "i have no complaints","i feel so so today","it was a forgettable day",
    "i am just existing","i feel blank","nothing triggered any emotion in me",
    "i am in autopilot mode","today was mediocre","i am okay nothing more than that",
    "i completed my tasks normally","everything is fine","i went about my day",
],
"anxiety": [
    "i am so anxious about everything","i cannot stop worrying at all","my mind is constantly racing",
    "i feel very nervous","i am overwhelmed with worry","i keep overthinking everything",
    "i feel completely on edge","i am panicking","i feel so restless","i cannot calm myself down",
    "i feel deeply uneasy","i am dreading what comes next","i feel a tight knot in my stomach",
    "my heart is racing fast","i feel very tense","i am totally stressed out",
    "i feel apprehensive about everything","i cannot relax at all","i feel wound up",
    "i am constantly worried about things","i feel impending doom approaching","i am catastrophizing",
    "i am hypervigilant","i feel constant and relentless worry","i am a nervous wreck",
    "i feel pressure all the time","i cannot stop the anxious thoughts","i feel very agitated",
    "i am on very high alert","i feel a sense of panic","i am bracing for the worst",
    "i feel worried all the time","i am sweating from anxiety","i feel my anxiety rising fast",
    "i am jittery and nervous","i feel tightness in my chest","i am anxious about everything",
    "i am trembling with anxiety","i feel anxious and scared","i am in constant deep dread",
    "i feel nervous all the time","i am on pins and needles","i feel very overwhelmed",
    "i am full of anxiety","i feel scared and anxious about tomorrow","i am always bracing",
    "i feel uncontrollable worry inside","i am anxious beyond all measure","i feel anxiety daily",
],
"love": [
    "i love you so much","i adore you completely","i am deeply in love with you",
    "you mean absolutely everything to me","i cherish you with all my heart",
    "i am completely devoted to you","my heart belongs entirely to you",
    "i feel such deep love for you","i am utterly smitten with you",
    "i love spending every moment with you","you are my everything in life",
    "i am completely head over heels for you","i feel so much affection for you",
    "i am romantically in love","i feel such warmth toward you",
    "i love you so very deeply","i am passionate about you","you light up my whole world",
    "i feel such tenderness for you","i am completely enamored with you",
    "i love you unconditionally","i feel such deep adoration","i am completely devoted",
    "you make my heart sing with joy","i feel such a deep connection with you",
    "i am falling more in love every day","i love you more and more each day",
    "i am completely bonded to you","you are my soulmate and partner",
    "i feel such passionate love for you","i am infatuated with you",
    "i love you with all of my heart","i feel true and real love for you",
    "i am completely yours","you complete me entirely","i feel overwhelming love",
    "i am so deeply in love","i love everything about who you are",
    "i feel love growing every single day","i am committed to loving you always",
    "you are the love of my entire life","i feel pure and real love",
    "i am lovesick for you","i love you so very tenderly",
    "i am completely crazy about you","i love you with such passion",
    "i am totally enchanted by you","i feel love so deeply every day",
],
"excitement": [
    "i am so incredibly excited","i just cannot wait for this","i am completely pumped up",
    "this is so thrilling","i feel absolutely electric","i am hyped about this",
    "i feel fully energized","i am buzzing with excitement","i am totally fired up",
    "i feel such great anticipation","i am very enthusiastic","i cannot contain my excitement",
    "i am completely stoked","i feel a huge rush","i am absolutely exhilarated",
    "i feel deeply thrilled","i am totally amped up","i feel completely charged up",
    "i am eagerly waiting for this","i feel such real excitement","i am so ready to go",
    "i feel a powerful surge of energy","i am completely keyed up","i feel wild excitement",
    "i am raring to go","i feel ecstatic with excitement","i am counting down the seconds",
    "i feel so pumped for this","i am giddy with excitement","i feel jittery excitement",
    "i am completely on fire about this","i feel tremendous excitement building",
    "i am jumping for joy","i feel totally electric excitement","i am thrilled beyond words",
    "i feel pure and real excitement","i am super excited about everything",
    "i feel an adrenaline rush","i am wildly excited","i feel excited and totally ready",
    "i am vibrating with all this energy","i feel explosive excitement","i am bursting with it",
    "i feel anticipation building inside","i am so eager for this","i feel incredible excitement",
    "i am overjoyed and excited","i feel alive with excitement","i am intensely excited",
],
"pride": [
    "i am so proud of myself","i feel deeply accomplished","i achieved my goal completely",
    "i earned every bit of this","i feel a deep sense of pride","i worked hard and succeeded",
    "i overcame every single obstacle","i feel dignified by my achievement",
    "i proved myself to everyone","i am proud of what i have built",
    "i feel completely worthy of this success","i stand tall with so much pride",
    "i surpassed my own expectations","i feel such confidence in my achievement",
    "i am proud of my entire team","i feel truly triumphant","i accomplished something truly great",
    "i am beaming with pride","i feel so validated by this","i made my family so proud",
    "i feel deeply honored","i am proud of how much i have grown",
    "i feel self respect from this","i am glowing with pride","i feel deep satisfaction",
    "i am deservedly proud of this","i feel proud of all my work",
    "i am recognized for all my effort","i feel so accomplished completely",
    "i am proud through and through","i feel the warmth of pride","i am honorably proud",
    "i feel fulfillment from my success","i am proud of my entire journey",
    "i feel pride in everything i achieved","i am genuinely and deeply proud",
    "i feel authentic real pride","i am overwhelmingly proud of this",
    "i feel pride rise up inside me","i am filled completely with pride",
    "i am standing so tall today","i feel inner pride deeply",
],
"shame": [
    "i am so deeply ashamed of myself","i feel utterly humiliated","i let everyone down badly",
    "i want to completely hide","i feel deeply embarrassed","i am completely disgraced",
    "i feel mortified by what i did","i wish i could just disappear","i feel deeply ashamed",
    "i am filled with burning shame","i feel completely exposed and ashamed",
    "i cannot face anyone around me","i feel like such a complete failure",
    "i am ashamed of all my actions","i feel such intense shame","i am publicly humiliated",
    "i feel deeply degraded","i am cringing with shame","i feel worthless from this shame",
    "i am deeply disgraced by this","i feel so shameful","i am overcome with deep shame",
    "i feel the burn of shame inside","i am embarrassed beyond any words",
    "i feel completely dishonored","i am so ashamed of everything",
    "i feel reduced by shame completely","i am devastated with shame",
    "i feel crushed by all this shame","i am ruined by embarrassment",
    "i feel the full weight of shame","i am shamed so deeply",
    "i feel humiliation so deeply","i am completely broken by shame","i feel stigmatized",
    "i am disgraced in front of everyone","i feel total disgrace","i am full of shame",
    "i feel regret and burning shame","i am drowning in deep shame",
    "i feel shame wash completely over me","i am marked by shame forever",
    "i am condemned by my shame","i feel deep and visible shame",
],
"guilt": [
    "i feel so terribly guilty","i should not have done that at all","i deeply regret my actions",
    "i hurt someone i really care about","i cannot forgive myself for this",
    "i feel terrible about what i did","it was completely my fault","i keep blaming myself",
    "i wish i could take it all back","the guilt is eating me alive inside",
    "i wronged someone i care about","i feel deep remorse","i owe them a sincere apology",
    "i feel deep and lasting guilt","i acted completely wrongly","i feel moral guilt inside",
    "i am responsible for the pain i caused","i torment myself over my terrible mistake",
    "i feel deeply regretful","i am consumed by guilt","i feel the heavy burden of guilt",
    "i did something very wrong","i feel guilty every single day","i cannot escape my guilt",
    "i feel awful for all my actions","i am guilty and i know it clearly",
    "i feel shame and deep guilt","i made a terrible mistake","i feel guilty deep inside",
    "i am haunted by guilt constantly","i feel ethical guilt","i am racked with guilt",
    "i feel guilty about hurting others","i caused real harm to someone",
    "i feel overwhelming guilt","i am guilty of wrongdoing","i feel deep self blame",
    "i am tormented by my guilt","i feel guilt without any relief","i am deeply sorry",
    "i feel deeply regretful for this","i am full of remorse","i am burdened by guilt",
    "i feel responsible and very guilty","i am morally guilty of this","i caused someone pain",
],
"envy": [
    "i envy their success so much","i wish i had what they have","i am jealous of their life",
    "why do they get everything good","i covet everything they have","i resent their good fortune",
    "i feel very envious of them","i want what they have badly","their success makes me feel small",
    "i am completely green with envy","i compare myself to them all the time",
    "i feel inadequate next to them","i want their recognition","i envy their talents deeply",
    "i feel bitter about their success","i resent all their advantages",
    "i want their opportunities so badly","i envy their entire lifestyle",
    "i feel a strong sting of envy","i am envious of their achievements",
    "i wish i were them completely","i envy their position","i feel envious of their wealth",
    "i covet their talent and skill","i feel left behind because of them",
    "i envy their relationships","i am jealous of their looks","i envy deeply",
    "i feel competitive envy toward them","i want what they have achieved",
    "i envy their happiness","i feel deep resentful envy","i am envious of their status",
    "i feel strong consuming envy","i envy their freedom","i wish i had their skills",
    "i envy their confidence","i feel deep burning envy","i am envious of their ease",
    "i want their good luck badly","i envy their social life","i feel bitter envy",
    "i am envious and resentful","i feel consuming envy daily","i envy their fame",
],
"gratitude": [
    "i am so truly grateful","thank you so very much","i feel truly and deeply blessed",
    "i appreciate you so deeply","i am thankful for absolutely everything",
    "your kindness means so much to me","i feel deep gratitude toward you",
    "thank you from the very bottom of my heart","i am so lucky to have you in my life",
    "i feel deeply and sincerely thankful","i appreciate all that you do",
    "i am grateful for all your help","i feel overwhelming gratitude",
    "thank you for always being there for me","i am humbled and so grateful",
    "i feel genuine and real thankfulness","i appreciate all your support so much",
    "i am grateful every single day","i feel such warm gratitude toward you",
    "thank you for changing my entire life","i am profoundly grateful for this",
    "i feel truly blessed and deeply thankful","i am grateful for this opportunity",
    "i thank you so very sincerely","i feel indebted with gratitude",
    "i am moved by your incredible generosity","i feel pure and real gratitude",
    "i am so very appreciative of you","i feel deeply thankful from my heart",
    "i am grateful to my very core","i feel recognition and deep thanks",
    "i am full of gratitude for you","i feel deep appreciation for everything",
    "i am grateful for your presence","i feel joyful gratitude today",
    "i am grateful for all the kindness","i feel authentic and real gratitude",
    "i am thankful for all my blessings","i feel grateful and deeply happy",
    "i am so very thankful for everything","i feel daily gratitude in my heart",
],
"hope": [
    "i believe things will get better soon","i am very hopeful about my future",
    "better days are definitely coming","i have faith that it will all improve",
    "i stay very optimistic about life","i trust that it will all work out",
    "i look forward to a better tomorrow","i hold onto hope every day",
    "i see the light ahead of me","i believe in good outcomes always",
    "i am completely filled with hope","i feel so hopeful about this",
    "things will improve i truly believe","i have hope for my future",
    "i trust the process completely","i am optimistic about everything ahead",
    "i feel a strong sense of hope","i believe in tomorrow deeply",
    "i have faith and real hope","i see real possibility ahead",
    "i am hopeful every single day","i feel genuinely encouraged by this",
    "i believe strongly in change","i have a very positive outlook",
    "i am hopeful despite all the difficulties","i feel hope rising inside me",
    "i believe in better days ahead","i hold hope so close to my heart",
    "i feel faith and deep hope","i am completely full of hope",
    "i trust that good things are coming","i feel optimistic and hopeful",
    "i believe strongly in progress","i am hopeful and very positive",
    "i feel sustained and lasting hope","i believe in real possibilities",
    "i am encouraged and very hopeful","i feel forward looking hope",
    "i am never without hope","i feel hopeful strength inside",
    "i trust in a much better future","i feel enduring hope every day",
],
"loneliness": [
    "i feel so completely alone","nobody understands how i feel","i have no one to talk to",
    "i feel totally isolated from everyone","everyone has left me behind",
    "i feel completely disconnected","i am so lonely","i feel utterly invisible",
    "no one ever reaches out to me","i ache for real connection",
    "i feel completely abandoned","i am all completely alone","i feel cut off from everyone",
    "the silence around me is deafening","i have no companion at all",
    "i feel profoundly and deeply alone","i am lonely every single day",
    "i feel socially isolated completely","i have no real friends","i feel excluded",
    "i am completely alone in this world","i feel so lonesome","i have nobody who cares",
    "i feel emotionally very alone","i am deeply lonely inside",
    "i feel unloved and so alone","i have nobody around me","i feel desperately lonely",
    "i am forgotten by everyone","i feel deep and real loneliness",
    "i am solitary and completely alone","i feel such empty loneliness",
    "i am painfully lonely every day","i feel chronically and deeply alone",
    "i have no meaningful connection","i feel alone even in a crowd",
    "i am isolated every single day","i feel the ache of loneliness constantly",
    "i am starved for real connection","i feel unloved completely",
    "i am completely and utterly alone","i feel profound isolation",
    "i feel lonely and so very sad","i am emotionally isolated",
],
"confusion": [
    "i have absolutely no idea what is happening","i am completely confused by all of this",
    "nothing at all makes sense to me","i do not understand any of this",
    "my mind is a complete mess","i am totally bewildered by this",
    "what is actually going on here","i feel completely lost",
    "i am so puzzled by everything","i feel deeply disoriented",
    "i cannot make sense of any of this","everything is completely contradictory",
    "i am so perplexed by this","i feel mentally very foggy",
    "i cannot follow the logic at all","i am completely mixed up",
    "i feel very uncertain about everything","i do not know what to think",
    "i am in a complete daze","i feel so confused all the time",
    "i cannot figure any of this out","i am completely baffled",
    "i feel so muddled inside","i am completely and totally lost",
    "i feel deep cognitive confusion","i cannot understand what happened",
    "i am in mental chaos","i feel confused every single day",
    "i am totally and completely bewildered","i feel such profound confusion",
    "i cannot make any decisions","i am spinning with confusion",
    "i feel like i am in a thick fog","i am very badly disoriented",
    "i cannot process this information","i feel confused and very lost",
    "i am hopelessly confused","i feel such mental confusion",
    "i am puzzled by absolutely everything","i feel very deep confusion",
    "i am unable to think clearly at all","i feel totally confounded",
],
"relief": [
    "i am so incredibly relieved","thank goodness it is finally over","i finally feel at ease",
    "the weight has been completely lifted","i can breathe freely again",
    "the very worst has now passed","what a huge relief this is",
    "i feel so much lighter now","all that terrible stress is completely gone",
    "i am so glad it worked out","i feel calm after all that worry",
    "all the anxiety is completely gone now","i exhale with complete relief",
    "all the tension melts away","i am no longer worried at all",
    "calm completely washes over me","i let go of all my fear",
    "peace finally returns to me","i feel such immense relief",
    "i am grateful that it is finally over","i feel completely unburdened",
    "the knot in my stomach finally loosened","i am so glad it did not get worse",
    "i feel genuine relief washing over me","relief flows warmly through me",
    "i smile knowing everything is okay","the resolution brings me real peace",
    "i breathe so much easier now","i feel rescued from all that stress",
    "calm replaces all my anxiety","i am so glad everything worked out",
    "i feel deep and genuine relief","i am truly and completely relieved",
    "i feel relief washing completely over me","i am freed from all that worry",
    "i feel such peaceful relief now","i am deeply and truly relieved",
    "i feel tranquil after all that stress","i am finally at peace",
    "i feel the relief of resolution","i am no longer tense at all",
    "i feel such profound relief","i am eased by the outcome",
],
"contempt": [
    "i have absolutely no respect for them","they are completely beneath me",
    "i look down on them completely","their behavior is truly pathetic",
    "i scoff at everything they do","they are not worth my time at all",
    "i feel only pure disdain for them","their arrogance is completely laughable",
    "i hold them in the very lowest regard","i feel total contempt for them",
    "i dismiss them completely and totally","pure disdain fills me toward them",
    "i regard them as totally inferior","their opinions deserve no consideration",
    "i despise their terrible behavior","i feel strong scorn for them",
    "their presence is completely beneath my notice","i have written them entirely off",
    "their incompetence deeply disgusts me","i sneer at all their attempts",
    "i have complete contempt for them","i treat them with total disdain",
    "i despise all their pretensions","they are beneath all my standards",
    "i cannot take them seriously at all","i feel very superior to them",
    "i have nothing but contempt for them","their behavior earns only scorn",
    "i regard them with total condescension","i feel contempt for them always",
    "i dismiss their worth completely","i view them only with contempt",
    "i feel disdain and total contempt","i am fully contemptuous of them",
    "i feel very strong contempt","i have utter contempt for them",
    "i feel condescension toward them strongly","i am full of contempt",
    "i feel profound contempt for them","i scorn all their actions",
    "i am dismissive with contempt","i feel contempt rising in me",
],
"boredom": [
    "i am so incredibly bored","absolutely nothing interests me at all","this is so very dull",
    "i have nothing at all to do","i am completely and utterly uninterested",
    "life is so monotonous right now","the same thing happens every single day",
    "this is so painfully boring","nothing excites me at all","i feel stuck in a deep rut",
    "time drags on so endlessly","everything around me is so tedious",
    "there is no spark left in my life","i scroll mindlessly out of boredom",
    "the routine is completely soul crushing","i feel totally unstimulated",
    "nothing at all captures my attention","i feel completely flat today",
    "i drift through days without any purpose","i am bored to complete frustration",
    "i wish something would actually happen","i feel hollow from all this monotony",
    "i am bored every single day","i feel deeply and profoundly bored",
    "i am chronically bored all the time","nothing at all stimulates me",
    "i feel the heavy weight of boredom","i am utterly and completely bored",
    "i feel profound and lasting boredom","i am intellectually very bored",
    "i feel dull and very bored","i am completely listless today",
    "i feel total and complete apathy","i am so weary from boredom",
    "i feel absolutely no excitement","i am terminally bored",
    "i feel so disengaged from everything","i am bored completely out of my mind",
    "i feel total and utter boredom","i am numbed completely by boredom",
    "i feel completely stagnant","i am desperately bored",
    "i feel constant and chronic boredom","i am empty and hollow from boredom",
],
"nostalgia": [
    "i miss the good old days so much","thinking of my childhood fills me with warmth",
    "i long deeply for the past","those memories are so precious to me",
    "i wish i could go back to those days","remembering feels so bittersweet",
    "i miss how things used to be","the old days were so much better",
    "i feel deeply nostalgic about the past","those memories make me so emotional",
    "i reminisce about the past fondly","i cherish every old memory",
    "life was so much simpler back then","time moved far too fast",
    "the past feels like a beautiful dream","i hold onto old memories so tightly",
    "remembering makes my heart ache sweetly","i long for those golden moments again",
    "old songs make me so nostalgic","i miss people from my past so much",
    "looking at old photos fills me with bittersweet longing",
    "i yearn deeply for those past days","nostalgia wraps warmly around me",
    "the good old times feel so far away","i ache for memories long gone",
    "the past gently calls to me","i feel nostalgic so very often",
    "i miss the innocence of my youth","i live in old memories fondly",
    "i feel warm and tender nostalgia","i miss my childhood friends deeply",
    "those were the absolute best days","i feel deep and warm nostalgia",
    "i long to relive the past again","old memories comfort me greatly",
    "i miss what once was so beautiful","the past feels like home to me",
    "i feel nostalgic sadness and warmth","i remember better times so fondly",
    "i feel wistful and nostalgic","i am nostalgic every single day",
    "i miss those simpler times deeply","i feel the gentle pull of nostalgia",
],
"jealousy": [
    "i am very jealous of their relationship","i cannot stand seeing them with others",
    "i feel possessive and jealous","i want to be the only one for them",
    "seeing them with someone else really hurts","i feel jealous in my relationship",
    "jealousy completely consumes me","i am burning with intense jealousy",
    "i cannot bear them choosing someone else","i feel very intense jealousy",
    "i watch them with burning jealousy","i am jealous of who they spend time with",
    "i feel relationship jealousy strongly","the jealousy tears me completely apart",
    "i am insecure and very jealous","i feel jealous of all their attention",
    "i want their full focus only on me","i feel threatened by everyone near them",
    "i am overcome completely with jealousy","jealousy makes me very possessive",
    "i feel deep romantic jealousy","i am jealous and very insecure",
    "jealousy completely ruins my peace","i feel deeply consuming jealousy",
    "i am jealous of all their other friends","i feel such deep jealousy inside",
    "i hate this jealous feeling i have","i am completely possessed by jealousy",
    "i feel irrational and overwhelming jealousy","i am jealous beyond my control",
    "i feel jealousy in my gut deeply","i am eaten alive by jealousy",
    "i feel intense possessive jealousy","i am devastated by jealousy",
    "i feel romantic possessiveness","i am wildly and intensely jealous",
    "i feel pain from deep jealousy","i am consumed by jealous thoughts",
    "i feel bitter and burning jealousy","i am shaken deeply by jealousy",
    "i feel the sharp sting of jealousy","i am broken completely by jealousy",
    "i feel hopeless jealousy","i am wracked completely by jealousy",
],
"frustration": [
    "this is so incredibly frustrating","i am so completely frustrated","nothing is working at all",
    "i keep failing over and over","i am at my absolute wits end","why will this not work",
    "i am completely fed up","my patience has completely run out","i have tried absolutely everything",
    "constant setbacks frustrate me deeply","i cannot make any progress",
    "i am beyond frustrated","this is completely impossible","i hit walls constantly",
    "i am exhausted by constant failure","nothing cooperates with me","i am so close to giving up",
    "frustration completely overwhelms me","i cannot get past this obstacle",
    "i feel completely and utterly defeated","why is this so incredibly difficult",
    "nobody understands my frustration","i cannot catch a single break",
    "absolutely everything goes wrong","i am sick of all these obstacles",
    "frustration keeps building and building","i feel like i am going nowhere",
    "this is maddeningly difficult","i am beyond annoyed and frustrated",
    "nothing about this works at all","i simply cannot progress",
    "the inability to succeed frustrates me","i pound my fists in frustration",
    "i cannot get anything right","i feel helpless frustration",
    "i am chronically and deeply frustrated","i feel constant frustration daily",
    "i am very deeply frustrated","i feel mounting frustration inside",
    "i am frustrated every single day","i feel pure frustration rising",
    "i am intensely frustrated","i feel building frustration inside",
    "i am utterly and completely frustrated","i feel the burn of frustration",
    "i am hopelessly frustrated","i feel deep and lasting frustration",
],
"awe": [
    "this is absolutely breathtaking","i am in complete and total awe",
    "this is absolutely stunning","i have never seen anything so beautiful",
    "the sheer scale fills me with awe","i feel truly amazed by this",
    "this is so magnificent","i stand in complete awe of this",
    "the beauty is completely beyond words","i am overwhelmed with wonder",
    "nature is so incredibly powerful","i feel humbled by its grandeur",
    "this is truly spectacular","i cannot believe how beautiful this is",
    "i feel pure and deep awe","the magnificence overwhelms me completely",
    "i feel reverence and deep awe","this is so grand and majestic",
    "the universe fills me with awe","i am struck completely dumb by its beauty",
    "this inspires such profound awe","i feel dwarfed by this magnificence",
    "the wonder is completely indescribable","i gaze in complete awe",
    "i feel connected to something so much greater","the stars fill me with wonder",
    "i am transfixed completely in awe","this is truly extraordinary",
    "i feel sacred and deep awe","i am gobsmacked by its majesty",
    "the beauty of the world truly awes me","this transcends everything i know",
    "i feel deeply moved and humbled","i am left breathless by all this wonder",
    "i feel such profound wonder","i am filled completely with reverence",
    "i feel deep spiritual awe","i am humbled by all this magnificence",
    "i feel cosmic awe inside me","i am completely awed by nature",
    "i feel wonder and deep awe","i am moved deeply by beauty",
    "i feel completely genuine awe","i am stunned by all this beauty",
    "i feel overwhelming awe inside","i am completely awed by this",
    "i feel awe at my very existence","i am awed by the entire universe",
],
"embarrassment": [
    "i am so embarrassed right now","my face is burning red with embarrassment",
    "i made a complete fool of myself","everyone saw my terrible mistake",
    "i just want to completely disappear","i am totally mortified by what happened",
    "i stumbled in front of everyone","i said completely the wrong thing",
    "i tripped very publicly","the embarrassment is completely unbearable",
    "i am cringing so hard right now","i feel completely humiliated",
    "i cannot face anyone after that","my cheeks are deeply flushed",
    "i said something very embarrassing","the whole room saw my mistake",
    "i cringe at what i just did","i feel so very self conscious",
    "i made such an awkward mistake","that was so utterly embarrassing",
    "i accidentally said something very wrong","i am blushing with embarrassment",
    "the awkward silence after my mistake","i fumbled and everyone noticed",
    "i feel waves of embarrassment","i spoke completely without thinking",
    "i made such an embarrassing error","i am red faced with shame",
    "i feel such deep embarrassment","i accidentally embarrassed myself badly",
    "that moment will haunt me forever","i stumbled over all my words",
    "i revealed something very embarrassing","i feel acute embarrassment",
    "i am thoroughly embarrassed by this","i feel social embarrassment",
    "i am painfully embarrassed","i feel the heat of embarrassment",
    "i am very deeply embarrassed","i feel public embarrassment strongly",
    "i am overcome with embarrassment","i feel exposed embarrassment",
    "i am so self conscious now","i feel burning embarrassment inside",
],
"grief": [
    "i am consumed completely by grief","the grief is truly unbearable",
    "i cannot accept that they are gone","grief sits on my chest so heavily",
    "i am in the very depths of grief","losing them left such a void in me",
    "grief comes in devastating waves","i cry whenever i think of them",
    "i cannot imagine life without them","grief completely stole my joy",
    "i feel their absence in every moment","the pain of this loss is immense",
    "i am deeply and truly grieving","grief transforms absolutely everything",
    "i feel completely lost without them","the grief is raw and still fresh",
    "i hold onto their memory tightly","i cannot move past all this grief",
    "grief hits me completely unexpectedly","i feel their absence so physically",
    "the finality deepens my grief daily","i am still grieving deeply",
    "grief has completely changed me","the world feels so wrong without them",
    "i wake up and grief floods back in","grief steals my sleep every night",
    "i grieve so very deeply","every milestone reminds me of my loss",
    "the grief simply does not end","i am undone completely by grief",
    "i feel grief so very constantly","the loss is so very profound",
    "grief and love feel the same thing","i sob deeply from grief",
    "i am learning to carry this grief","i feel permanent grief inside",
    "i am heartbroken with deep grief","i feel endless grief every day",
    "i am completely overwhelmed by grief","i feel such acute grief",
    "i am shattered completely by grief","i feel complicated unresolved grief",
    "i am devastated completely by loss","i feel deep grief every day",
    "i am broken completely by bereavement","i feel grief like an open wound",
],
}

texts, labels = [], []
for emotion, sentences in raw.items():
    for s in sentences:
        texts.append(s)
        labels.append(emotion)

print(f"Total samples : {len(texts)}")
print(f"Emotions      : {len(raw)}")
print(f"Avg per class : {len(texts)//len(raw)}")

X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.15, random_state=42, stratify=labels
)

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        ngram_range=(1, 3),
        max_features=25000,
        sublinear_tf=True,
        min_df=1,
        strip_accents='unicode',
        analyzer='word'
    )),
    ('clf', LogisticRegression(max_iter=5000, C=15.0, solver='lbfgs'))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
acc = accuracy_score(y_test, y_pred)

joblib.dump(pipeline, 'emotion_model_27.pkl')

print(f"\nAccuracy : {acc:.4f} ({acc*100:.1f}%)")
print(classification_report(y_test, y_pred, zero_division=0))